### ISSUE TITLE
Feature Request: Do not include punctuation in wordlist

### ISSUE THREAD

**Issue by Shreeshrii** [wincentbalin/pytesstrain#1]
The wordlists in tesseract-ocr/langdata do not have punctuation marks (except for - dash).

create_dictdata creates a wordlist but it has the punctuation marks. Example:

```
Prasamar.
ṭyul(tana)
‘pertaining
to’;
Nandaka
auxiliary
deities.
Bhānugupta,
```

Request wordlists to not include punctuation marks.
Thanks!

**Comment by wincentbalin** [comment]
Hello Shree, I changed the default behaviour of `create_dictdata.py` to remove punctuation.

**Comment by Shreeshrii** [comment]
Thank you so much for your prompt response. Working great!!
